import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "Demos",
      items: [
        {
          type: "doc",
          label: "Demos",
          id: "demos/demos",
        },
        {
          type: "link",
          label: "Storybook Instance",
          href: "https://headless-tree.lukasbach.com/storybook/react/",
        },
      ],
    },
    {
      type: "category",
      label: "API",
      items: [
        {
          type: "link",
          label: "Tree Config",
          href: "/api/core/interface/TreeConfig",
        },
        {
          type: "link",
          label: "Tree Instance",
          href: "/api/core/interface/TreeInstance",
        },
        {
          type: "link",
          label: "Item Instance",
          href: "/api/core/interface/ItemInstance",
        },
        {
          type: "link",
          label: "Tree State",
          href: "/api/core/interface/TreeState",
        },
        {
          type: "link",
          label: "Full API",
          href: "/api/core",
        },
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
