name: Snapshot Release
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ./.yarn/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
      - uses: volta-cli/action@v4.1.1
        with:
          registry-url: "https://registry.npmjs.org"

      - run: yarn
      - run: yarn lint:test
      - run: yarn test
      - run: yarn build:core
      - run: yarn build:web

      - name: Snapshot Versioning
        run: yarn changeset version --snapshot

      - name: Snapshot Release
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            exit 0
          else
            yarn changeset publish --no-git-tag --tag branch
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
