name: Verify
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ./.yarn/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
      - uses: volta-cli/action@v4.1.1
      - run: yarn
      - run: yarn lint:test
      - run: yarn test
      - run: yarn build:core
      - run: yarn build:web
